insert into users(name,surname,username,email,password) values('John','Doe','user','john@gmail.com','password')
insert into users(name,surname,username,email,password) values('John2','Doe2','user','john2@gmail.com','password')
insert into users(name,surname,username,email,password) values('John3','Doe3','user','john3@gmail.com','password')
insert into users(name,surname,username,email,password) values('John4','Doe4','user','john4@gmail.com','password')
insert into users(name,surname,username,email,password) values('John5','Doe5','user','john5@gmail.com','password')